name = "kreida-wasm-chart"
target = "../../target/wasm32-unknown-emscripten"

build:
	mkdir -p out
	rm -rf {{target}}/release/deps/*.wasm
	rm -rf {{target}}/release/{{name}}.js
	cargo build --release --target=wasm32-unknown-emscripten
	cp {{target}}/release/{{name}}.js out/{{name}}.js
	cp {{target}}/release/deps/*.wasm out/{{name}}.wasm
	cp assets/static/* out/
	emrun out/index.html

debug:
	mkdir -p out
	rm -rf {{target}}/debug/deps/*.wasm*
	rm -rf {{target}}/debug/{{name}}.js
	cargo build --target=wasm32-unknown-emscripten
	cp {{target}}/debug/{{name}}.js out/{{name}}.js
	cp {{target}}/debug/deps/*.wasm out/{{name}}.wasm
	cp {{target}}/debug/deps/*.wasm.map out/{{name}}.wasm.map
	cp assets/static/* out/
	emrun out/index.html
