server {
    listen 80;
    server_name _;

    location / {
        root /srv/www/;
        try_files $uri =404;
        expires max;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /static/healthz {
        default_type text/plain;
        return 200 "ok";
    }
}
